spring:
  mail:
    host: smtp.163.com
    port: 25
    username: jason18826233123@163.com
    password: AEYLSTBDBLEXGGRG            #授权码，不是邮箱登录密码
    default-encoding: UTF-8
    properties:
      mail: 
       smtp:
        auth: true
        starttls:
          enable: true
          required: true
server:
  port: 9001